package com.dyalog.apldev.debug.core.model;

/**
 * Listeners are notified of events occurint in a APL program
 * being interpreted.
 * <p>
 * The events generated by the interpreter are:
 * <ul>
 * <li><code>started</code> -- the interpreter has started (guaranteed to be the
 * 	first event sent)</li>
 * <li><code>terminated</code> -- the interpreter has terminated</li>
 * </ul>
 */
public interface IAPLEventListener {
	
	/**
	 * Notification the given event occurred in the target program
	 * being interpreted.
	 * 
	 * @param event the event
	 */
	public void handleEvent(String event);

}
